# frozen_string_literal: true


source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

ruby '>2.5.0'

gem "github-pages", group: :jekyll_plugins
gem 'bundler'
gem 'just-the-docs'